name: Noliter-Server-Manager
version: '${project.version}'
main: kr.kro.teambucket.kurumi.noliterservermanager.Main
api-version: 1.18
depend: [ProtocolLib]

commands:
  noliter:
    description: 노리터 커맨드
