name: Noliter-Server-Manager
version: '${project.version}'
main: kr.kro.teamdodoco.rumi.plugin.noliterservermanager.Main
api-version: 1.21
depend: [ProtocolLib], [NBTAPI]

commands:
  noliter:
    description: 노리터 커맨드
